SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

CREATE TABLE administration.codes (
    id bigint NOT NULL,
    available boolean NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    expired_at timestamp without time zone NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE administration.codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE administration.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE administration.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE administration.users (
    id bigint NOT NULL,
    amount_successful_logins integer,
    created_at timestamp without time zone NOT NULL,
    email character varying(100) NOT NULL,
    enabled boolean NOT NULL,
    first_name character varying(100) NOT NULL,
    last_login timestamp without time zone,
    last_name character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    updated_at timestamp without time zone,
    username character varying(100) NOT NULL
);

ALTER TABLE administration.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE administration.users_x_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);

INSERT INTO administration.roles VALUES (1, 'ADMINISTRADOR');
INSERT INTO administration.roles VALUES (2, 'GESTOR');
INSERT INTO administration.roles VALUES (3, 'OPERADOR');
INSERT INTO administration.roles VALUES (4, 'PROVEEDOR INSUMO');
INSERT INTO administration.roles VALUES (5, 'SUPER ADMINISTRADOR');

INSERT INTO administration.users VALUES (1, NULL, '2022-04-04 16:44:02.932', 'root@st.com', true, 'Super', NULL, 'Administración', '$2a$10$BN0swx1H2z15eXKeoVKclOr6smEakVRozJQV1r6BOJ17Wed71sE7O', NULL, 'root');

INSERT INTO administration.users_x_roles VALUES (1, 5);

SELECT pg_catalog.setval('administration.codes_id_seq', 1, false);
SELECT pg_catalog.setval('administration.roles_id_seq', 5, true);
SELECT pg_catalog.setval('administration.users_id_seq', 1, true);

ALTER TABLE ONLY administration.codes
    ADD CONSTRAINT codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY administration.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY administration.users
    ADD CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE ONLY administration.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY administration.users_x_roles
    ADD CONSTRAINT fk5m3oxlveydoa436r304vaaehn FOREIGN KEY (user_id) REFERENCES administration.users(id);

ALTER TABLE ONLY administration.users_x_roles
    ADD CONSTRAINT fk60659q5rov7mrdxwbmkc6156y FOREIGN KEY (role_id) REFERENCES administration.roles(id);

ALTER TABLE ONLY administration.codes
    ADD CONSTRAINT fk8ry3r9xl1dqixqp9dyrxehcsq FOREIGN KEY (user_id) REFERENCES administration.users(id);